#!bin/sh

# Yet Another Wifi Auto Connect (YAWAC)
# https://github.com/mehdichaouch/YAWAC

# This config file is use by yawac.sh

# Background internet connection checking interval
ConnCheckTimer=60

# After new network is set, time to wait for network to establish, before checking if it's working
# If too low the router may be still waiting for the dhcp assignment from the main router, causing the script to discard the network
NewConnCheckTimer=25

# Set a random MAC each boot
randMac="1"

# Address to ping to test connectivity
ping_addr="google.fr"

# FreeWifi parameters
freewifi_ssid="FreeWifi"
freewifi_login=""
freewifi_password=""
freewifi_url_auth="https://wifi.free.fr/Auth"
freewifi_connexion_reussie="CONNEXION AU SERVICE REUSSIE"
freewifi_timeout=10

# Set the wifi

net1_ssid="Galaxy S6"
net1_encryption="psk2"
net1_key="nomore70"

net2_ssid="McDonald's France"
net2_encryption="none"

net3_ssid="MonitoringCP"
net3_encryption="psk2"
net3_key="0bcababa"

net4_ssid="FreeWifi"
net4_encryption="none"

net5_ssid="McDonald's France"
net5_encryption="none"

net6_ssid="McDonald's free Wifi"
net6_encryption="none"

net7_ssid="McDo Free WiFi"
net7_encryption="none"

net8_ssid="McDonalds Wifi Gratis"
net8_encryption="none"

net9_ssid="Total_Free_WiFi"
net9_encryption="none"

net10_ssid="HITKundenWLAN"
net10_encryption="none"

net11_ssid="Telekom"
net11_encryption="none"

net12_ssid="TOTAL-WIFI"
net12_encryption="none"

net13_ssid="WGRL"
net13_encryption="psk2"
net13_key="4865426486"

net44_ssid="Darmowe_Orange_WiFi"
net44_encryption="none"

net99_ssid="MyWifiNetwork2"
net99_encryption="psk"
net99_key="BigCheese"
net99_macaddr="11:22:33:44:55:66"
